<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{
	public function run()
{
		$rows = [	
			[
				'id' => '36',
				'user_id' => '50',
				'reference' => 'Z1utYxitpC',
				'amount' => '1200.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'hhk',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Pick Up',
				'location' => '9',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '',
				'delivery_location' => '',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:47:29',
				'updated_at' => '2020-05-09 10:47:29',

			],

			[
				'id' => '35',
				'user_id' => '49',
				'reference' => 'maW7MxXRlB',
				'amount' => '1300.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'fks',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '800',
				'delivery_location' => '24',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:38:58',
				'updated_at' => '2020-05-09 10:38:58',

			],

			[
				'id' => '34',
				'user_id' => '48',
				'reference' => 'JK3M7BVpov',
				'amount' => '10150.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'No special packaging',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:34:12',
				'updated_at' => '2020-05-09 10:34:12',

			],

			[
				'id' => '33',
				'user_id' => '47',
				'reference' => '5pWbwk88iz',
				'amount' => '10600.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'Not available',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:32:01',
				'updated_at' => '2020-05-09 10:32:01',

			],

			[
				'id' => '32',
				'user_id' => '46',
				'reference' => 'MPdplu2uX9',
				'amount' => '10700.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'none',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:27:32',
				'updated_at' => '2020-05-09 10:27:32',

			],

			[
				'id' => '31',
				'user_id' => '45',
				'reference' => '6MzykAseFG',
				'amount' => '10000.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'note really',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 09:46:39',
				'updated_at' => '2020-05-09 09:46:39',

			],

			[
				'id' => '30',
				'user_id' => '44',
				'reference' => 'At397nmdox',
				'amount' => '3650.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'nol',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '3000',
				'delivery_location' => '8',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 01:49:27',
				'updated_at' => '2020-05-09 01:49:27',

			],

			[
				'id' => '28',
				'user_id' => '42',
				'reference' => '5EXtGF7eyG',
				'amount' => '1450.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'no',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '950',
				'delivery_location' => '22',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 01:15:42',
				'updated_at' => '2020-05-09 01:15:42',

			],

			[
				'id' => '29',
				'user_id' => '43',
				'reference' => 'KKqL6mYxYM',
				'amount' => '10000.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'boor',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 01:20:36',
				'updated_at' => '2020-05-09 01:20:36',

			],

			[
				'id' => '37',
				'user_id' => '51',
				'reference' => 'B2PjI03lUT',
				'amount' => '1100.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'nui',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Pick Up',
				'location' => '7',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '',
				'delivery_location' => '',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:50:22',
				'updated_at' => '2020-05-09 10:50:22',

			],

			[
				'id' => '38',
				'user_id' => '52',
				'reference' => '4ZWgbBADvK',
				'amount' => '820.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'h',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Pick Up',
				'location' => '5',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '',
				'delivery_location' => '',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:52:28',
				'updated_at' => '2020-05-09 10:52:28',

			],

			[
				'id' => '39',
				'user_id' => '53',
				'reference' => 'pwVaa75CgY',
				'amount' => '9900.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'jk',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 10:55:25',
				'updated_at' => '2020-05-09 10:55:25',

			],

			[
				'id' => '40',
				'user_id' => '54',
				'reference' => 'zp27cahHKF',
				'amount' => '13100.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'Excellent',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 11:02:49',
				'updated_at' => '2020-05-09 11:02:52',

			],

			[
				'id' => '41',
				'user_id' => '55',
				'reference' => '3ume7VHib6',
				'amount' => '12200.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'Perfect',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 11:05:10',
				'updated_at' => '2020-05-09 11:05:13',

			],

			[
				'id' => '42',
				'user_id' => '56',
				'reference' => 'R5WUKf7WQG',
				'amount' => '11600.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'card',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'Card',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => 'T774572936907685',
				'created_at' => '2020-05-09 11:09:21',
				'updated_at' => '2020-05-09 11:09:21',

			],

			[
				'id' => '43',
				'user_id' => '57',
				'reference' => 'LqxFsX52d3',
				'amount' => '10150.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'no special packing',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 11:34:22',
				'updated_at' => '2020-05-09 11:34:26',

			],

			[
				'id' => '44',
				'user_id' => '58',
				'reference' => 'qYzR0SEdS3',
				'amount' => '10150.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'no',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 11:46:09',
				'updated_at' => '2020-05-09 11:46:18',

			],

			[
				'id' => '45',
				'user_id' => '59',
				'reference' => '0Hbq8Xw42c',
				'amount' => '10150.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => '',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'USSD',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-09 12:18:14',
				'updated_at' => '2020-05-09 12:18:19',

			],

			[
				'id' => '54',
				'user_id' => '3',
				'reference' => 'Xwghz8NMVJ',
				'amount' => '11750.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'kij',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '4',
				'visibility' => '',
				'payment_type' => 'Card',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '0',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '3',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => 'T200045916217988',
				'created_at' => '2020-05-18 21:40:30',
				'updated_at' => '2020-05-18 21:42:23',

			],

			[
				'id' => '53',
				'user_id' => '2',
				'reference' => 'niQCKrsbDT',
				'amount' => '4150.00',
				'discount' => '',
				'name' => 'Dev Chris',
				'address' => '',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => 'Patient',
				'patient_name' => 'Christopher Okokon Ntuk',
				'patient_phone' => '8183780409',
				'patient_address' => '',
				'note' => '',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Pick Up',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'Wallet',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '',
				'delivery_location' => '',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '2',
				'beneficiary_address' => '',
				'beneficiary_phone' => '8183780409',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '2',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-14 10:11:08',
				'updated_at' => '2020-05-14 10:11:08',

			],

			[
				'id' => '52',
				'user_id' => '67',
				'reference' => 'dBXA0orzfj',
				'amount' => '1100.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'ah',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Pick Up',
				'location' => '9',
				'visibility' => '',
				'payment_type' => 'Access Bank - IOPTYTASY',
				'status' => 'Paid',
				'delivery_status' => '1',
				'delivery_price' => '',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-12 17:01:22',
				'updated_at' => '2020-05-13 17:55:24',

			],

			[
				'id' => '51',
				'user_id' => '66',
				'reference' => 'sROHWIItef',
				'amount' => '11750.00',
				'discount' => '0',
				'name' => 'Christopher Okokon Ntuk',
				'address' => '6 School road, off Itu road, Uyo',
				'pickup_date' => '',
				'pickup_time' => '',
				'prescribed_for' => '',
				'patient_name' => '',
				'patient_phone' => '',
				'patient_address' => '',
				'note' => 'afj',
				'cart' => '',
				'phone' => '08183780409',
				'email' => 'engchris95@gmail.com',
				'delivery_method' => 'Home Delivery',
				'location' => '',
				'visibility' => '',
				'payment_type' => 'Bank Transfer',
				'status' => 'Unpaid',
				'delivery_status' => '1',
				'delivery_price' => '9500',
				'delivery_location' => '1',
				'transfer_id' => '',
				'push_id' => '',
				'prescription' => '',
				'beneficiary_address' => '',
				'beneficiary_phone' => '',
				'beneficiary' => '',
				'address_2' => '',
				'address_3' => '',
				'order_from' => '0',
				'delivery_assign' => '',
				'recipient_name' => '',
				'recipient_phone' => '',
				'recipient_address' => '',
				'payment_reference' => '',
				'created_at' => '2020-05-12 16:59:40',
				'updated_at' => '2020-05-12 16:59:40',

			],

		];
		foreach ($rows as $row) {
			DB::table('Orders')->insert($row);
		}
	}
}