<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
	public function run()
{
		$rows = [	
			[
				'id' => '1',
				'name' => 'Christopher Okokon Ntuk',
				'email' => 'root@ehis.com',
				'phone' => '08183780409',
				'address' => '6 School road, off Itu road, Uyo, Donatus street, Off RCC Road, Benin-Agbor Road, Benin City, Edo State',
				'password' => '$2y$10$p09xKGc/nDSMCUfhg0a/5ulBPJoWM6LhYe01sMJXnHHPFeaehJn9e',
				'role_id' => '1',
				'status' => '',
				'cac_reg_numb' => '72b2u3bi',
				'nationality' => 'Nigeria',
				'state' => 'Akwa ibom',
				'remember_token' => '3lkNEmc4hcVxEm15965lMmB6PTZad2Tr1W6uYPgqnv6bwx5AOUNC76i7WJ6S',
				'access_token' => '',
				'created_at' => '2020-02-25 12:39:55',
				'updated_at' => '2020-04-21 11:26:47',

			],

			[
				'id' => '2',
				'name' => 'Dev Chris',
				'email' => 'engchris95@gmail.com',
				'phone' => '08183780409',
				'address' => '6 School road, off Itu road, Uyo',
				'password' => '$2y$10$p09xKGc/nDSMCUfhg0a/5ulBPJoWM6LhYe01sMJXnHHPFeaehJn9e',
				'role_id' => '2',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => 'v9PmBJXgFfPPxf87v99Lwu2pNB5uacA2HrOy39FpsUTsMsU4OV28qN8GgZwr',
				'access_token' => '',
				'created_at' => '2020-02-25 14:16:11',
				'updated_at' => '2020-02-25 14:16:11',

			],

			[
				'id' => '3',
				'name' => 'Christopher Okokon Ntuk',
				'email' => 'root@gmail.com',
				'phone' => '08183780409',
				'address' => '',
				'password' => '$2y$10$p09xKGc/nDSMCUfhg0a/5ulBPJoWM6LhYe01sMJXnHHPFeaehJn9e',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => 'CVqAHd9dDZNGuhiK9ejSB8VVTyphPKnE2ObVTuA3bhVBCJHSAU21njxiYCZD',
				'access_token' => '',
				'created_at' => '2020-04-04 14:50:33',
				'updated_at' => '2020-04-04 14:50:33',

			],

			[
				'id' => '11',
				'name' => 'user',
				'email' => '7NyMzEiS@gmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-04 15:10:32',
				'updated_at' => '2020-05-04 15:10:32',

			],

			[
				'id' => '12',
				'name' => 'user',
				'email' => '7Ushyk4A@yahoo.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-04 15:43:35',
				'updated_at' => '2020-05-04 15:43:35',

			],

			[
				'id' => '13',
				'name' => 'user',
				'email' => 'ebYpiimX@outlook.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-04 19:32:57',
				'updated_at' => '2020-05-04 19:32:57',

			],

			[
				'id' => '14',
				'name' => 'user',
				'email' => 'U4vXMubv@outlook.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 11:21:09',
				'updated_at' => '2020-05-06 11:21:09',

			],

			[
				'id' => '10',
				'name' => 'NetSurge',
				'email' => 'j.bosco@gmail.com',
				'phone' => '09057041663',
				'address' => 'Suite SC9 Sparkle plaza off first Avenue Gwarinpa. FCT Abuja Nigeria',
				'password' => '$2y$10$A4VfescGeKQvKL0iWjacHu16eqkJefCSG1ndTfmN0JdC5.dYcZ3AK',
				'role_id' => '1',
				'status' => '',
				'cac_reg_numb' => 'RC345334564',
				'nationality' => 'Nigeria',
				'state' => 'FCT',
				'remember_token' => 'xq3KKN4PjKgFlb7qwbulxzYHjuMofVDSuCCXSR0XeIYlaodvoRtPd1iKFd56',
				'access_token' => '',
				'created_at' => '2020-04-27 18:20:52',
				'updated_at' => '2020-04-27 18:20:52',

			],

			[
				'id' => '15',
				'name' => 'user',
				'email' => 'MrtSGRfG@outlook.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 11:31:19',
				'updated_at' => '2020-05-06 11:31:19',

			],

			[
				'id' => '16',
				'name' => 'user',
				'email' => '3daAYxO8@gmail.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 11:50:27',
				'updated_at' => '2020-05-06 11:50:27',

			],

			[
				'id' => '17',
				'name' => 'user',
				'email' => 'Wl8K7vvr@gmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 11:54:42',
				'updated_at' => '2020-05-06 11:54:42',

			],

			[
				'id' => '18',
				'name' => 'user',
				'email' => 'eh0GRdv9@gmail.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 12:04:15',
				'updated_at' => '2020-05-06 12:04:15',

			],

			[
				'id' => '19',
				'name' => 'user',
				'email' => 'Sowjh0iv@gmail.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 12:12:22',
				'updated_at' => '2020-05-06 12:12:22',

			],

			[
				'id' => '20',
				'name' => 'user',
				'email' => 'aMnVn0vt@yahoo.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-06 12:23:10',
				'updated_at' => '2020-05-06 12:23:10',

			],

			[
				'id' => '21',
				'name' => 'user',
				'email' => 'dwjcHAVa@yahoo.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-08 22:52:49',
				'updated_at' => '2020-05-08 22:52:49',

			],

			[
				'id' => '22',
				'name' => 'user',
				'email' => 'mUTzHzIl@gmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-08 23:46:03',
				'updated_at' => '2020-05-08 23:46:03',

			],

			[
				'id' => '23',
				'name' => 'user',
				'email' => '2n1Ty1Jq@gmail.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:05:42',
				'updated_at' => '2020-05-09 00:05:42',

			],

			[
				'id' => '24',
				'name' => 'user',
				'email' => '6PfQ3z2H@outlook.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:07:42',
				'updated_at' => '2020-05-09 00:07:42',

			],

			[
				'id' => '25',
				'name' => 'user',
				'email' => 'R3z0FhX6@protonmail.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:14:59',
				'updated_at' => '2020-05-09 00:14:59',

			],

			[
				'id' => '26',
				'name' => 'user',
				'email' => 'J9PoCd0W@gmail.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:21:48',
				'updated_at' => '2020-05-09 00:21:48',

			],

			[
				'id' => '27',
				'name' => 'user',
				'email' => 'AFRIdstS@outlook.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:27:19',
				'updated_at' => '2020-05-09 00:27:19',

			],

			[
				'id' => '28',
				'name' => 'user',
				'email' => 'i4BSZdMl@protonmail.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:30:47',
				'updated_at' => '2020-05-09 00:30:47',

			],

			[
				'id' => '29',
				'name' => 'user',
				'email' => 'hwMj6jh6@gmail.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:33:29',
				'updated_at' => '2020-05-09 00:33:29',

			],

			[
				'id' => '30',
				'name' => 'user',
				'email' => 'kym7AuFm@protonmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:40:27',
				'updated_at' => '2020-05-09 00:40:27',

			],

			[
				'id' => '31',
				'name' => 'user',
				'email' => 'CxoRbKGc@protonmail.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:43:20',
				'updated_at' => '2020-05-09 00:43:20',

			],

			[
				'id' => '32',
				'name' => 'user',
				'email' => 'DE0CPnZN@outlook.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:46:01',
				'updated_at' => '2020-05-09 00:46:01',

			],

			[
				'id' => '33',
				'name' => 'user',
				'email' => 'H2x3SgXk@outlook.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:46:37',
				'updated_at' => '2020-05-09 00:46:37',

			],

			[
				'id' => '34',
				'name' => 'user',
				'email' => 'E45gs49f@outlook.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:48:23',
				'updated_at' => '2020-05-09 00:48:23',

			],

			[
				'id' => '35',
				'name' => 'user',
				'email' => 'nWAHGH9B@yahoo.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:50:12',
				'updated_at' => '2020-05-09 00:50:12',

			],

			[
				'id' => '36',
				'name' => 'user',
				'email' => 'qsUs3cpn@gmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:52:30',
				'updated_at' => '2020-05-09 00:52:30',

			],

			[
				'id' => '37',
				'name' => 'user',
				'email' => 'fRzQGP5P@yahoo.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 00:56:46',
				'updated_at' => '2020-05-09 00:56:46',

			],

			[
				'id' => '38',
				'name' => 'user',
				'email' => 'WyHZijoI@gmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:02:03',
				'updated_at' => '2020-05-09 01:02:03',

			],

			[
				'id' => '39',
				'name' => 'user',
				'email' => 'IqhVHISz@yahoo.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:06:53',
				'updated_at' => '2020-05-09 01:06:53',

			],

			[
				'id' => '40',
				'name' => 'user',
				'email' => '0C9zAO0u@yahoo.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:09:08',
				'updated_at' => '2020-05-09 01:09:08',

			],

			[
				'id' => '41',
				'name' => 'user',
				'email' => '6bhBRyJF@gmail.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:13:36',
				'updated_at' => '2020-05-09 01:13:36',

			],

			[
				'id' => '42',
				'name' => 'user',
				'email' => '4dVpBEM3@gmail.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:15:42',
				'updated_at' => '2020-05-09 01:15:42',

			],

			[
				'id' => '43',
				'name' => 'user',
				'email' => 'i8dpvKHM@outlook.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:20:36',
				'updated_at' => '2020-05-09 01:20:36',

			],

			[
				'id' => '44',
				'name' => 'user',
				'email' => 'BVLDYSOE@gmail.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 01:49:27',
				'updated_at' => '2020-05-09 01:49:27',

			],

			[
				'id' => '45',
				'name' => 'user',
				'email' => 'jKXYxTJN@gmail.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 09:46:39',
				'updated_at' => '2020-05-09 09:46:39',

			],

			[
				'id' => '46',
				'name' => 'user',
				'email' => 'v8I0tLvy@outlook.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:27:32',
				'updated_at' => '2020-05-09 10:27:32',

			],

			[
				'id' => '47',
				'name' => 'user',
				'email' => 'BaFH4mhi@outlook.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:32:01',
				'updated_at' => '2020-05-09 10:32:01',

			],

			[
				'id' => '48',
				'name' => 'user',
				'email' => 'kZyS0J5O@protonmail.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:34:12',
				'updated_at' => '2020-05-09 10:34:12',

			],

			[
				'id' => '49',
				'name' => 'user',
				'email' => 'FwWxhOPF@yahoo.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:38:58',
				'updated_at' => '2020-05-09 10:38:58',

			],

			[
				'id' => '50',
				'name' => 'user',
				'email' => 'le3jS6wR@gmail.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:47:29',
				'updated_at' => '2020-05-09 10:47:29',

			],

			[
				'id' => '51',
				'name' => 'user',
				'email' => '0B8gLY22@gmail.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:50:22',
				'updated_at' => '2020-05-09 10:50:22',

			],

			[
				'id' => '52',
				'name' => 'user',
				'email' => 'PL0vgaKX@gmail.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:52:28',
				'updated_at' => '2020-05-09 10:52:28',

			],

			[
				'id' => '53',
				'name' => 'user',
				'email' => 'iLbgb1b3@outlook.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 10:55:25',
				'updated_at' => '2020-05-09 10:55:25',

			],

			[
				'id' => '54',
				'name' => 'user',
				'email' => 'RSKYYtTo@outlook.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 11:02:49',
				'updated_at' => '2020-05-09 11:02:49',

			],

			[
				'id' => '55',
				'name' => 'user',
				'email' => '9GOOLE72@outlook.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 11:05:10',
				'updated_at' => '2020-05-09 11:05:10',

			],

			[
				'id' => '56',
				'name' => 'user',
				'email' => '7ce3xytI@outlook.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 11:09:21',
				'updated_at' => '2020-05-09 11:09:21',

			],

			[
				'id' => '57',
				'name' => 'user',
				'email' => 'RVmF8rnj@gmail.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 11:34:22',
				'updated_at' => '2020-05-09 11:34:22',

			],

			[
				'id' => '58',
				'name' => 'user',
				'email' => 'JLEquoJN@outlook.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 11:46:09',
				'updated_at' => '2020-05-09 11:46:09',

			],

			[
				'id' => '59',
				'name' => 'user',
				'email' => 'j3OWozbE@gmail.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-09 12:18:14',
				'updated_at' => '2020-05-09 12:18:14',

			],

			[
				'id' => '60',
				'name' => 'user',
				'email' => 'GlefJ4P8@protonmail.ai',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:06:05',
				'updated_at' => '2020-05-12 16:06:05',

			],

			[
				'id' => '61',
				'name' => 'user',
				'email' => 'PiggV1JU@outlook.org',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:41:22',
				'updated_at' => '2020-05-12 16:41:22',

			],

			[
				'id' => '62',
				'name' => 'user',
				'email' => '3b6n207q@yahoo.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:56:34',
				'updated_at' => '2020-05-12 16:56:34',

			],

			[
				'id' => '63',
				'name' => 'user',
				'email' => 'ldlSYN6B@outlook.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:57:38',
				'updated_at' => '2020-05-12 16:57:38',

			],

			[
				'id' => '64',
				'name' => 'user',
				'email' => 'H3hOQUnt@outlook.tech',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:57:41',
				'updated_at' => '2020-05-12 16:57:41',

			],

			[
				'id' => '65',
				'name' => 'user',
				'email' => 'tnVxkVwI@gmail.com',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:58:36',
				'updated_at' => '2020-05-12 16:58:36',

			],

			[
				'id' => '66',
				'name' => 'user',
				'email' => 'BHFgKeG9@gmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 16:59:40',
				'updated_at' => '2020-05-12 16:59:40',

			],

			[
				'id' => '67',
				'name' => 'user',
				'email' => 'VBLxId0y@protonmail.net',
				'phone' => 'user',
				'address' => '',
				'password' => 'user',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-05-12 17:01:22',
				'updated_at' => '2020-05-12 17:01:22',

			],

			[
				'id' => '68',
				'name' => 'ibrahim',
				'email' => 'abdulsamadibrahim210@gmail.com',
				'phone' => '',
				'address' => '',
				'password' => '$2y$10$O9C1WTP24Y1hgVN6xB2fduBz2S9wnloYdJYq22iRc.owl34Qvqx1y',
				'role_id' => '0',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-06-08 12:35:44',
				'updated_at' => '2020-06-08 12:35:44',

			],

			[
				'id' => '69',
				'name' => 'Eddy john',
				'email' => 'eddy@gmail.com',
				'phone' => '09059297073',
				'address' => 'addies house',
				'password' => '$2y$10$pm/2bDoJx2XqDUmzGQEJye5mmN2la3NylK1gNY.Vt2Tyu1jno70Ha',
				'role_id' => '2',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-06-09 09:34:13',
				'updated_at' => '2020-06-09 09:34:13',

			],

			[
				'id' => '70',
				'name' => 'Eddy john',
				'email' => 'eddys@gmail.com',
				'phone' => '09059297073',
				'address' => 'addies house',
				'password' => '$2y$10$1hIuQqMA3zLzfB7Cc2wOcO8BShYFYF8vqAzA3Ks1eqNm8c4KsoSJa',
				'role_id' => '2',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-06-09 09:35:49',
				'updated_at' => '2020-06-09 09:35:49',

			],

			[
				'id' => '71',
				'name' => 'Jude',
				'email' => 'edds@gmail.com',
				'phone' => '08059297073',
				'address' => 'Garki',
				'password' => '$2y$10$vST.10s7gClEueEGAcdpuuP7VBuiSus3ruZP9zuF0d/K6WRwPnFZC',
				'role_id' => '2',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => 'Nigerian',
				'state' => 'Abuja',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-06-09 09:36:16',
				'updated_at' => '2020-06-09 09:44:41',

			],

			[
				'id' => '72',
				'name' => 'Eddy john',
				'email' => 'eddi@gmail.com',
				'phone' => '09059297073',
				'address' => 'addies house',
				'password' => '$2y$10$j/mihsgs7CXqsk..4D9bY.kvON6bz22gheNgJZLSGKW5BpLCrU/5y',
				'role_id' => '2',
				'status' => '',
				'cac_reg_numb' => '',
				'nationality' => '',
				'state' => '',
				'remember_token' => '',
				'access_token' => '',
				'created_at' => '2020-06-09 14:06:27',
				'updated_at' => '2020-06-09 14:06:27',

			],

		];
		foreach ($rows as $row) {
			DB::table('Users')->insert($row);
		}
	}
}